// utils/videoTranscript.js
// Transcribes a Cloudinary video using AssemblyAI (free tier: 5 hrs/month)
// then generates a downloadable PDF.
//
// Setup:
//   1. Go to https://www.assemblyai.com and create a free account
//   2. Copy your API key from the dashboard
//   3. Add to Railway env vars:  ASSEMBLYAI_API_KEY=your_key_here
//   4. Run:  npm install pdfkit

const ASSEMBLYAI_API = 'https://api.assemblyai.com/v2';

// ── Step 1: Submit video URL for transcription ────────────────────────────────
const submitTranscription = async (videoUrl) => {
  const res = await fetch(ASSEMBLYAI_API + '/transcript', {
    method:  'POST',
    headers: {
      authorization:  process.env.ASSEMBLYAI_API_KEY,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      audio_url:    videoUrl,
      speech_models: ["universal-2"],  // required by AssemblyAI current API
      punctuate:    true,
      format_text:  true,
    }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error('AssemblyAI submit failed: ' + (err.error || JSON.stringify(err) || res.status));
  }

  const data = await res.json();
  return data.id; // transcript job ID
};

// ── Step 2: Poll until transcription is complete ──────────────────────────────
const pollTranscription = async (transcriptId, maxWaitMs = 300000) => {
  const start    = Date.now();
  const interval = 5000; // check every 5 seconds

  while (Date.now() - start < maxWaitMs) {
    await new Promise(r => setTimeout(r, interval));

    const res = await fetch(ASSEMBLYAI_API + '/transcript/' + transcriptId, {
      headers: { authorization: process.env.ASSEMBLYAI_API_KEY },
    });

    if (!res.ok) throw new Error('AssemblyAI poll failed: ' + res.status);

    const data = await res.json();

    if (data.status === 'completed') return data.text;
    if (data.status === 'error')     throw new Error('Transcription failed: ' + data.error);
    // status === 'processing' or 'queued' — keep polling
  }

  throw new Error('Transcription timed out. The video may be too long. Try again in a few minutes.');
};

// ── Step 3: Generate PDF from transcript text ─────────────────────────────────
const buildPdf = (lesson, course, transcriptText) => {
  let PDFDocument;
  try { PDFDocument = require('pdfkit'); }
  catch { throw new Error('pdfkit not installed. Run: npm install pdfkit'); }

  return new Promise((resolve, reject) => {
    const doc    = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data',  c  => chunks.push(c));
    doc.on('end',   () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header ───────────────────────────────────────────────────────────────
    doc.fontSize(20).font('Helvetica-Bold')
       .text('EduAdapt — Lesson Transcript', { align: 'center' });
    doc.moveDown(0.4);
    doc.fontSize(15).font('Helvetica-Bold')
       .text(lesson.title, { align: 'center' });
    doc.fontSize(11).font('Helvetica').fillColor('#555')
       .text('Course: ' + (course?.title || 'N/A'), { align: 'center' });
    doc.text('Generated: ' + new Date().toLocaleDateString('en-GB', {
      day: '2-digit', month: 'long', year: 'numeric'
    }), { align: 'center' });
    doc.moveDown(0.8);

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ddd');
    doc.moveDown(0.8);

    // ── Transcript body ───────────────────────────────────────────────────────
    doc.fontSize(11).font('Helvetica').fillColor('#222').lineGap(5);

    // Break into readable paragraphs at sentence boundaries (~500 chars)
    const words      = transcriptText.split(' ');
    const paragraphs = [];
    let   current    = '';
    for (const word of words) {
      current += (current ? ' ' : '') + word;
      if (current.length >= 500 && (word.endsWith('.') || word.endsWith('?') || word.endsWith('!'))) {
        paragraphs.push(current);
        current = '';
      }
    }
    if (current) paragraphs.push(current);

    paragraphs.forEach(p => { doc.text(p); doc.moveDown(0.6); });

    // ── Footer ────────────────────────────────────────────────────────────────
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#bbb')
       .text('Transcript auto-generated by AssemblyAI. Accuracy may vary.', { align: 'center' });

    doc.end();
  });
};

// ── Main export ───────────────────────────────────────────────────────────────
const generateTranscriptPdf = async (lesson, course) => {
  if (!process.env.ASSEMBLYAI_API_KEY) {
    throw new Error(
      'ASSEMBLYAI_API_KEY is not set. '
      + 'Sign up free at https://assemblyai.com and add the key to your Railway environment variables.'
    );
  }

  const videoUrl = lesson.videoOriginal;
  if (!videoUrl) throw new Error('This lesson has no video uploaded yet.');

  const transcriptId = await submitTranscription(videoUrl);
  const text         = await pollTranscription(transcriptId);

  if (!text || !text.trim()) {
    throw new Error('Transcript is empty. The video may have no speech.');
  }

  return buildPdf(lesson, course, text);
};

module.exports = { generateTranscriptPdf };